# Generated by Django 5.2.7 on 2025-10-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('hobbies', models.CharField(max_length=200)),
                ('skills', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LearningJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('example_code', models.TextField(blank=True, null=True)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
